# Shared build and runtime identity for the typed Rust exporter.
RUST_EXPORTER_TOOLCHAIN=nightly-2026-06-16
RUST_EXPORTER_TARGET=x86_64-unknown-linux-gnu
RUST_EXPORTER_COMPILER_COMMIT=01dfd79246f1b2d5f146616deff08223a840a9ae
RUST_EXPORTER_SYSROOT="${RUSTUP_HOME:-$HOME/.rustup}/toolchains/$RUST_EXPORTER_TOOLCHAIN-$RUST_EXPORTER_TARGET"
RUST_EXPORTER_UPDATE_HASH="${RUSTUP_HOME:-$HOME/.rustup}/update-hashes/$RUST_EXPORTER_TOOLCHAIN-$RUST_EXPORTER_TARGET"
